public with sharing class NewApexClass {
    public NewApexClass() {

    }


    public String sayHello(){
        System.debug('Hello World');
        System.debug('Added by Vinod');

    }

   String s= 'Mahesh' ;//added a string
    public Void sayHello(String s){
        system.debug('Name is :' +s);//debugging 
   
        


    }
// added by mahesh Branch 
    public static void methodByMahesh(){
        System.debug('Added by mahesh');
    }


// added by mahesh Branch 
//added by 2nd method
public static void secondMethodByMahesh(){
    System.debug('Added by mahesh');
}

public static void methodAddedByVinod(){

    System.debug('Added by Vinod');
}
    //System.debug('Added by Vinod Borikar');
   


// added by mahesh Branch 
//added by 3rd method
public static void thirdMethodByMahesh(){
    System.debug('Added by mahesh');
}

}    





