public with sharing class NewApexClass {
    public NewApexClass() {

    }
 //vinod

    public String sayHello(){
        System.debug('Hello World');
        System.debug('Added by Vinod');

    }

   String s= 'Mahesh' ;//added a string
    public Void sayHello(String s){
        system.debug('Name is :' +s);//debugging 
   
        
 //main
    }
// added by mahesh Branch 
    public static void methodByMahesh(){
        System.debug('Added by mahesh');
    }
}
