public with sharing class NewApexClass {
    public NewApexClass() {

    }


    public String sayHello(){
        System.debug('Hello World');
        System.debug('Added by Vinod');

    }

   String s= 'Mahesh' ;//added a string
    public Void sayHello(String s){
        system.debug('Name is :' +s);//debugging 
   
        


    }
// added by mahesh Branch 
    public static void methodByMahesh(){
        System.debug('Added by mahesh');
    }
}


    }
}
}

